# Generated by Django 4.0.4 on 2022-05-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_events',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phase_count', models.PositiveSmallIntegerField()),
                ('mag_type', models.CharField(max_length=10)),
                ('depth', models.CharField(max_length=10)),
                ('event_datetime', models.DateTimeField()),
                ('region', models.CharField(max_length=150)),
                ('bulletin_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=2)),
                ('is_fake', models.BooleanField()),
                ('is_inside', models.BooleanField()),
                ('source', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earthquake_events',
            },
        ),
        migrations.CreateModel(
            name='earthquake_settings',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('simulation', models.BooleanField(default=0)),
                ('number_events', models.PositiveSmallIntegerField()),
                ('auto_send', models.BooleanField(default=0)),
                ('auto_send_email', models.TextField()),
                ('filter_1', models.BooleanField(default=0)),
                ('filter_2', models.BooleanField(default=0)),
                ('filter_3', models.BooleanField(default=0)),
                ('filter_4', models.BooleanField(default=0)),
                ('inside_aoi', models.BooleanField(default=0)),
                ('show_aor', models.BooleanField(default=0)),
                ('show_aoi', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'earthquake_settings',
            },
        ),
    ]
