# Generated by Django 4.0.2 on 2022-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_bulletins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=50, null=True)),
                ('rbtype_id', models.IntegerField(default=0, null=True)),
                ('bulletin_no', models.IntegerField(default=0, null=True)),
                ('_precise_id', models.IntegerField(default=0, null=True)),
                ('_time_sec', models.IntegerField(default=0, null=True)),
                ('_body', models.TextField(default='', null=True)),
                ('_eqinfo_json', models.TextField(default='', null=True)),
                ('_precise_info', models.TextField(default='', null=True)),
                ('_sealvl_info', models.TextField(default='', null=True)),
                ('_inun_id', models.TextField(default='', null=True)),
                ('_in_scs', models.IntegerField(default=0, null=True)),
                ('_precise_eqref', models.IntegerField(default=0, null=True)),
                ('_usgs_shakecast_url', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'earthquake_bulletins',
            },
        ),
        migrations.CreateModel(
            name='earthquake_events',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phase_count', models.PositiveSmallIntegerField(default=0)),
                ('mag_type', models.CharField(max_length=10)),
                ('depth', models.CharField(max_length=10)),
                ('event_datetime', models.DateTimeField()),
                ('region', models.CharField(max_length=150)),
                ('bulletin_no', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.CharField(default='N', max_length=2, null=True)),
                ('is_fake', models.BooleanField(default=False, null=True)),
                ('is_inside', models.BooleanField(default=False, null=True)),
                ('source', models.CharField(default='RIMES', max_length=10, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'earthquake_events',
            },
        ),
        migrations.CreateModel(
            name='earthquake_settings',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('simulation', models.BooleanField(default=0)),
                ('number_events', models.PositiveSmallIntegerField()),
                ('auto_send', models.BooleanField(default=0)),
                ('auto_send_email', models.TextField(default='', null=True)),
                ('filter_1', models.BooleanField(default=0)),
                ('filter_2', models.BooleanField(default=0)),
                ('filter_3', models.BooleanField(default=0)),
                ('filter_4', models.BooleanField(default=0)),
                ('inside_aoi', models.BooleanField(default=0)),
                ('show_aor', models.BooleanField(default=0)),
                ('show_aoi', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'earthquake_settings',
            },
        ),
    ]
