# Generated by Django 4.0.4 on 2022-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0002_alter_earthquake_settings_auto_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_events',
            name='bulletin_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='is_fake',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='is_inside',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='phase_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='source',
            field=models.CharField(default='RIMES', max_length=10),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='status',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
