# Generated by Django 4.0.4 on 2022-05-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0003_alter_earthquake_events_bulletin_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_bulletins',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mag_type', models.CharField(max_length=50)),
                ('rbtype_id', models.IntegerField(default=0)),
                ('bulletin_no', models.IntegerField(default=0)),
                ('_precise_id', models.IntegerField(default=0)),
                ('_time_sec', models.IntegerField(default=0)),
                ('_body', models.TextField(default='', null=True)),
                ('_eqinfo_json', models.TextField(default='', null=True)),
                ('_precise_info', models.TextField(default='', null=True)),
                ('_sealvl_info', models.TextField(default='', null=True)),
                ('_inun_id', models.TextField(default='', null=True)),
                ('_in_scs', models.CharField(max_length=100)),
                ('_precise_eqref', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'earthquake_bulletins',
            },
        ),
    ]
