# Generated by Django 4.0.4 on 2022-05-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0004_earthquake_bulletins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_bulletins',
            old_name='mag_type',
            new_name='event_id',
        ),
    ]
