# Generated by Django 4.0.4 on 2022-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0005_rename_mag_type_earthquake_bulletins_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='_in_scs',
            field=models.IntegerField(default=0),
        ),
    ]
