# Generated by Django 4.0.4 on 2022-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0006_alter_earthquake_bulletins__in_scs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_events',
            old_name='is_inside',
            new_name='is_insides',
        ),
    ]
