# Generated by Django 4.0.4 on 2022-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0007_rename_is_inside_earthquake_events_is_insides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_events',
            old_name='is_insides',
            new_name='is_inside',
        ),
    ]
