# Generated by Django 4.0.4 on 2022-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0008_rename_is_insides_earthquake_events_is_inside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_bulletins',
            old_name='_in_scs',
            new_name='_in_scss',
        ),
    ]
