# Generated by Django 4.0.4 on 2022-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0009_rename__in_scs_earthquake_bulletins__in_scss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_bulletins',
            old_name='_in_scss',
            new_name='_in_scs',
        ),
    ]
