# Generated by Django 4.0.4 on 2022-05-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0010_rename__in_scss_earthquake_bulletins__in_scs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_events',
            name='bulletin_no',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
