# Generated by Django 4.0.4 on 2022-05-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0011_alter_earthquake_events_bulletin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_events',
            name='source',
            field=models.CharField(default='RIMES', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='status',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
    ]
