# Generated by Django 4.0.4 on 2022-05-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0012_alter_earthquake_events_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_events',
            name='is_fake',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='is_inside',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
