# Generated by Django 4.0.4 on 2022-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0013_alter_earthquake_events_is_fake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake_events',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_events',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
