# Generated by Django 4.0.4 on 2022-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0014_alter_earthquake_events_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake_bulletins',
            name='_usgs_shakecast_url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='_in_scs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='_precise_eqref',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='_precise_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='_time_sec',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='bulletin_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='event_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='earthquake_bulletins',
            name='rbtype_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
