# Generated by Django 4.0.2 on 2022-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='observation_metdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(db_column='country_id', max_length=10)),
                ('station_name', models.CharField(max_length=128)),
                ('date_data', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_t', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_t', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'observation_metdata',
            },
        ),
        migrations.CreateModel(
            name='weather_forecast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_data', models.DateField()),
                ('province_name', models.CharField(max_length=128)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('windspeed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'weather_forecast',
            },
        ),
    ]
