# Generated by Django 4.0.2 on 2022-03-29 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_observation_metdata_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation_metdata',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='weather.country'),
        ),
    ]
