"""
Django settings for SDC project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1-59q&b26(l2oxru5h_6+-8hq@5%%gom29^owawyq)4*q$s^aj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['203.159.16.180','203.159.16.134','sdc.rimes.int','localhost']
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.weather', # If you create app in folder dont forget to change the name in apps.py in your app folder too.
	'app.disaster_ana',
    'app.earthquake', 
    'app.api',
    'app.report_n_project',
    'app.sdc_auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SDC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SDC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Connect to postgreSQL database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'SDC_project.sqlite3',
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'SDC_project', 
#        'USER': 'postgres', 
#        'PASSWORD': '87654321',
#        'HOST': '127.0.0.1', 
#        'PORT': '5432',

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"), 
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email

EMAIL = {
    'PORT': '465',
    #'USER': 'satark@rimes.int', 
    'USER': 'sdcportal@rimes.int', 
    'FROM': 'no-reply@rimes.int', 
    #'PASSWORD': 'zaurzlrqmjoikiuk', 
    'PASSWORD': 'xeeidtlirkihmnkd',
    'HOST': 'smtp.gmail.com',
    'NAME': 'Eartquake Advisory',
}

### Set mail for SDC system ###
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST = 'ssl://smtp.googlemail.com'
EMAIL_USE_TLS = True
#EMAIL_PORT = 587
EMAIL_PORT = 465

EMAIL_HOST_USER='sdcportal@rimes.int'
EMAIL_HOST_PASSWORD='xeeidtlirkihmnkd'

### Login / Logout ###
LOGIN_REDIRECT_URL = "weather_forecast"
LOGOUT_REDIRECT_URL = "login"


BULLETIN = {
    'directory' : os.path.join(BASE_DIR, 'bulletins/'),
    'ORGANIZATION' : 'Swiss Agency for Development and Corporations (SDC)',
    'ORG_SHORT' : 'SDC',
}

# PUSHER API KEY
PUSHER = {
    'KEY': 'e302dd7a74caf028800a',
    'CLUSTER': 'ap1',
    'CHANNEL': 'satark',
    'EVENT': 'earthquake',
}