# Generated by Django 4.0.2 on 2022-05-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_id', models.CharField(max_length=10)),
                ('province_name', models.CharField(max_length=128)),
                ('district_id', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=128)),
                ('commune_id', models.CharField(max_length=10)),
                ('commune_name', models.CharField(max_length=128)),
                ('date_data', models.DateField()),
                ('event', models.CharField(max_length=128)),
                ('datacard_records', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('injured', models.IntegerField()),
                ('missing', models.IntegerField()),
                ('house_destroy', models.IntegerField()),
                ('house_damage', models.IntegerField()),
                ('directly_affected', models.IntegerField()),
                ('indirectly_affected', models.IntegerField()),
                ('relocated', models.IntegerField()),
                ('evacuated', models.IntegerField()),
                ('losses_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('losses_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_centers', models.IntegerField()),
                ('hospitals', models.IntegerField()),
                ('damages_crops_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_sector', models.CharField(max_length=128)),
                ('glide_number', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'disaster',
            },
        ),
    ]
