# Generated by Django 4.0.2 on 2022-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdc_project_cambodia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=256)),
                ('objective', models.CharField(max_length=512)),
                ('duration', models.CharField(max_length=256)),
                ('budget', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('partners', models.CharField(max_length=256)),
                ('outcome', models.CharField(max_length=512)),
                ('pdf_download', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sdc_project_cambodia',
            },
        ),
    ]
